language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -r requirements.txt
script:
    - python -m unittest

# matrix:
#     include:
#         - os: linux
#           python: '3.4'
#         - python: '3.5'
#         - python: '3.6'
#         - python: '3.7'

